CREATE DATABASE IF NOT EXISTS JKEDB;
GRANT ALL PRIVILEGES ON JKEDB.* TO 'jke_user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON JKEDB.* TO 'jke_user'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;